//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PicMember
    {
        public int ID { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
